### ISSUE TITLE
Conflicts with Drush

### ISSUE THREAD

**Issue by legolasbo** [mglaman/drupalorg-cli#11]
This package can't be installed when drush is globally installed via composer. This is caused by the fact that one of drush's dependencies requires symfony/console `~2.7|^3` while this requires `^4`. Any chance that this package could also work with `symfony/console ^3`?

**Comment by mglaman** [comment]
I thought Drush isn't supposed to be installed globally at all anymore, or at least not via Composer?

I can see about knocking it back. I just wanted to get improvements.

**Comment by mglaman** [comment]
Also, would it be worth just getting this packaged as a phar that can update itself?

**Comment by legolasbo** [comment]
Packaging it up as a phar could be a great solution :)

**Comment by mglaman** [comment]
:) Cool! I'll do that.

**Comment by mglaman** [comment]
Phars are now available https://github.com/mglaman/drupalorg-cli/releases/tag/v0.0.8

Need to document such.

**Comment by mglaman** [comment]
🎉 updated README

**Comment by legolasbo** [comment]
Works like a charm! 👍
