### ISSUE TITLE
Latest release 0.3.1 is missing the drupalorg.phar file

### ISSUE THREAD

**Issue by jameswilson** [mglaman/drupalorg-cli#130]
https://github.com/mglaman/drupalorg-cli/releases/latest currently redirects to https://github.com/mglaman/drupalorg-cli/releases/tag/0.3.1  but there is no drupalorg.phar file attached in the assets section.   All previous releases have 3 assets (a phar, a source.tgz and a source.zip file).  This release has only 2 assets (the source.tgz and source.zip).

**Comment by mglaman** [comment]
Closing, as automated uploads have been added.
