### ISSUE TITLE
Uncaught TypeError Argument 1

### ISSUE THREAD

**Issue by Greg-Boggs** [mglaman/drupalorg-cli#170]
I cleaned out my .config folder completely and installed drupalorg cli fresh

When I run drupalorg MRN I get this error on PHP 7.4.

User error maybe?

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Symfony\Component\Process\Process::__construct() must be of the type array, string given, called in /home/me/.config/composer/vendor/klaussilveira/gitter/lib/Gitter/Client.php on line 82 and defined in /home/me/.config/composer/vendor/symfony/process/Process.php:143

**Comment by NickDickinsonWilde** [comment]
Looks like that dependency doesn't support symfony/process 5 or 6.

Short term fix if you're composer required (ie not using the .phar):
```composer require "symfony/process:v4.4.41 as v5.0.0"```
That may interfer with other things - but does fix release-notes.

**Comment by Greg-Boggs** [comment]
++

**Comment by ivnish** [comment]
Same problem

**Comment by dillix** [comment]
@mglaman I got same error in 0.4.1. Now drupalorg mrn don't work. I tried both methods: deprecated composer global and phar. So I temporary downgraded to 0.3.3.

**Comment by mglaman** [comment]
klaussilveira/gitter probably needs to be abandoned as it still has a low symfony/process dependency. Sorry, I'll look into this.

**Comment by andypost** [comment]
That's the issue with `klaussilveira/gitter` which requires `symfony/proces ^2.8` but app installing SF 5/6

**Comment by andypost** [comment]
@mglaman maybe https://www.drupal.org/project/drupal/issues/3172537 could help but ++ to get rid of outdated dependency

**Comment by rmcveigh** [comment]
++ to get rid of the outdated dependency

**Comment by AdamPS** [comment]
Thanks @chrfritsch - it would be great to get this one in😃

**Comment by NickDickinsonWilde** [comment]
@mglaman any chance of a look at #183 and a new release soon? thanks!
