### ISSUE TITLE
phar not generated for 0.4.0 version

### ISSUE THREAD

**Issue by FlorentTorregrosa** [mglaman/drupalorg-cli#172]
Hi,

I have just noticed that https://github.com/mglaman/drupalorg-cli/releases/download/0.4.0/drupalorg.phar is in 404.

While https://github.com/mglaman/drupalorg-cli/releases/download/0.3.3/drupalorg.phar is ok.

Version 0.3.1 also had the problem.

**Comment by nevergone** [comment]
@mglaman ping! :)

**Comment by nevergone** [comment]
root@0366368ac50f:/app/drupalorg-cli-0.4.0# composer box-build
> php box.phar compile

    ____
   / __ )____  _  __
  / __  / __ \| |/_/
 / /_/ / /_/ />  <
/_____/\____/_/|_|


Box version 4.0.2@4a57707 2022-06-27 07:11:00 UTC

 // Loading the configuration file "/app/drupalorg-cli-0.4.0/box.json".                                                 

🔨  Building the PHAR "/app/drupalorg-cli-0.4.0/drupalorg.phar"

? Registering compactors
  + KevinGH\Box\Compactor\Php
? Adding main file: /app/drupalorg-cli-0.4.0/drupalorg
? Adding requirements checker
? Adding binary files
    > No file found
? Auto-discover files? No
? Exclude dev files? Yes
? Adding files
    > 567 file(s)
? Generating new stub
  - Using shebang line: #!/usr/bin/env php
  - Using banner:
    > Generated by Humbug Box 4.0.2@4a57707.
    > 
    > @link https://github.com/humbug/box
? Dumping the Composer autoloader

In ComposerOrchestrator.php line 90:
                                  
  Could not dump the autoloader.  
                                  

In ComposerOrchestrator.php line 90:
                                                                                                                                                                                            
  The command "'/usr/local/bin/composer' 'dump-autoload' '--classmap-authoritative' '--no-dev' '--ansi'" failed.                                                                            
                                                                                                                                                                                            
  Exit Code: 1(General error)                                                                                                                                                               
                                                                                                                                                                                            
  Working directory: /tmp/box/Box42402                                                                                                                                                      
                                                                                                                                                                                            
  Output:                                                                                                                                                                                   
  ================                                                                                                                                                                          
                                                                                                                                                                                            
                                                                                                                                                                                            
  Error Output:                                                                                                                                                                             
  ================                                                                                                                                                                          
                                                                                                                                                                                            
  In AutoloadGenerator.php line 1384:                                                                                                                                               
                                                                                                                                                                              
    require(/tmp/box/Box42402/vendor/phpstan/phpstan/bootstrap.php): Failed to open stream: No such file or directory                                                         
                                                                                                                                                                              
                                                                                                                                                                                            
  dump-autoload [-o|--optimize] [-a|--classmap-authoritative] [--apcu] [--apcu-prefix APCU-PREFIX] [--dev] [--no-dev] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-r  
  eqs]                                                                                                                                                                                  
                                                                                                                                                                                            

compile [--debug] [--no-parallel] [--no-restart] [--dev] [--no-config] [--with-docker] [-c|--config CONFIG] [-d|--working-dir WORKING-DIR]

Script php box.phar compile handling the box-build event returned with error code 1

**Comment by dillix** [comment]
Is there any news?

**Comment by mglaman** [comment]
Sorry, I am checking it in #177.

**Comment by mglaman** [comment]
It should be fixed in https://github.com/mglaman/drupalorg-cli/releases/tag/0.4.1 release

**Comment by FlorentTorregrosa** [comment]
Thanks @mglaman!
