### ISSUE TITLE
PHP 8.2 Deprecated:  Using ${var} in strings is deprecated

### ISSUE THREAD

**Issue by markdorison** [mglaman/drupalorg-cli#188]
When installing `drupalorg-cli` via the [phar method listed in the README](https://github.com/mglaman/drupalorg-cli#installing-manually), and running on PHP 8.2, the `symfony/console` dependency triggers the following deprecations:
```
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in phar:///usr/local/bin/drupalorg/vendor/symfony/console/Command/DumpCompletionCommand.php on line 48

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in phar:///usr/local/bin/drupalorg/vendor/symfony/console/Command/DumpCompletionCommand.php on line 48
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in phar:///usr/local/bin/drupalorg/vendor/symfony/console/Command/DumpCompletionCommand.php on line 56

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in phar:///usr/local/bin/drupalorg/vendor/symfony/console/Command/DumpCompletionCommand.php on line 56
```

After cloning the repo and running `composer install` the version of `symfony/console` that is installed is v5.4.8. Despite the [allowance of 6.0 in the `symfony/console` composer requirements](https://github.com/mglaman/drupalorg-cli/blob/43949e6dc068abf888fe5b5b462de2511489b41b/composer.json#L18), a 6.x version is not able to be installed as PHP 8.0 is needed and [Composer config is overriding the locally installed version with 7.4](https://github.com/mglaman/drupalorg-cli/blob/43949e6dc068abf888fe5b5b462de2511489b41b/composer.json#L43-L45):

https://github.com/mglaman/drupalorg-cli/blob/43949e6dc068abf888fe5b5b462de2511489b41b/composer.json#L43-L45

I believe this could be resolved by removing or updating that Composer configuration and packaging a new release, though I am unsure if that would break things for folks still on PHP 7.4.

**Comment by mglaman** [comment]
yeah it's pinned for minimum version support. I think it's probably safe to say the tool requires PHP 8.1 locally.

**Comment by mglaman** [comment]
Went for PHP 8.1, symfony/console bumped with https://github.com/mglaman/drupalorg-cli/pull/194
