### ISSUE TITLE
Improve release notes formatting

### ISSUE THREAD

**Issue by damienmckenna** [mglaman/drupalorg-cli#21]
I used the script to generate a summary on a new project release:
* https://www.drupal.org/project/exif_custom/releases/7.x-1.21

Looking at the formatting of the release notes, a few things could be improved:
* There's no need for a h3 that just says "Summary: [version]", which would appear right under where it says "Release notes".
* It might be useful to start off with a section to be filled in that says e.g. `<p><em>fill in a summary here</em></p>` to encourage the maintainer to summarize it all.
* There should be a h3 above the itemized release notes that says e.g. "Full changelog" or something.

**Comment by mglaman** [comment]
Ditching

> There's no need for a h3 that just says "Summary: [version]", which would appear right under where it says "Release notes".

and doing 

> There should be a h3 above the itemized release notes that says e.g. "Full changelog" or something.

sounds good to me.

> It might be useful to start off with a section to be filled in that says e.g. <p><em>fill in a summary here</em></p> to encourage the maintainer to summarize it all.

I was considering this, too. Or having some way to always prefill some generic text. For instance, we have an upgrade WTF to document each time

> <p>Please follow the updating instructions provided in our documentation: https://docs.drupalcommerce.org/commerce2/developer-guide/install-update/updating</p>
