### ISSUE TITLE
Trying to get property 'nodeValue' of non-object in phar

### ISSUE THREAD

**Issue by heddn** [mglaman/drupalorg-cli#26]
while executing:
`$ drupalorg mi heddn`

PHP Notice:  Trying to get property 'nodeValue' of non-object in phar://~/bin/drupalorg/src/Cli/Command/Maintainer/Issues.php on line 64
PHP Stack trace:
PHP   1. {main}() ~/bin/drupalorg:0
PHP   2. require() ~/bin/drupalorg:10
PHP   3. mglaman\DrupalOrgCli\Application->run() phar://~/bin/drupalorg/drupalorg:17
PHP   4. mglaman\DrupalOrgCli\Application->doRun() phar://~/bin/drupalorg/vendor/symfony/console/Application.php:148
PHP   5. mglaman\DrupalOrgCli\Application->doRunCommand() phar://~/bin/drupalorg/vendor/symfony/console/Application.php:248
PHP   6. mglaman\DrupalOrgCli\Command\Maintainer\Issues->run() phar://~/bin/drupalorg/vendor/symfony/console/Application.php:946
PHP   7. mglaman\DrupalOrgCli\Command\Maintainer\Issues->execute() phar://~/bin/drupalorg/vendor/symfony/console/Command/Command.php:252
PHP   8. mglaman\DrupalOrgCli\Command\Maintainer\Issues->getIssueStatus() phar://~/bin/drupalorg/src/Cli/Command/Maintainer/Issues.php:53
PHP   9. mglaman\DrupalOrgCli\Command\Maintainer\Issues->getIssueValue() phar://~/bin/drupalorg/src/Cli/Command/Maintainer/Issues.php:68

**Comment by mglaman** [comment]
Argh. That is an RSS feed and looks like the parser is busted.

It has HTML and `$nodes = $xpath->query("//div[contains(@class,\"$class\")]//div");` isn't working.
