### ISSUE TITLE
The number of issues is not correct

### ISSUE THREAD

**Issue by adrian-cid** [mglaman/drupalorg-cli#27]
The number of issues is not correct when I used the command `maintainer:release-notes` it show me 72 issues solved but I only have 49.

**Comment by adrian-cid** [comment]
You can see it at https://www.drupal.org/project/onlyone/releases/8.x-1.6

**Comment by mglaman** [comment]
![commits_for_allow_a_content_type_only_once__only_one____drupal_org](https://user-images.githubusercontent.com/3698644/39631057-d0483cfa-4f76-11e8-992a-4cd1d94c94ee.png)

I see the problem. There were multiple commits for an issue. So we'll want to make the list of node IDs extract unique.
