### ISSUE TITLE
THANK YOU!

### ISSUE THREAD

**Issue by wimleers** [mglaman/drupalorg-cli#33]
I just wanted to say thanks :)

You've solved a lot of hassle with `drupalorg mrn oldtag newtag`. I am now looking forward to tagging a release instead of dreading the manual labor:
- https://www.drupal.org/project/jsonapi/releases/8.x-2.0
- https://www.drupal.org/project/jsonapi/releases/8.x-2.1
- https://www.drupal.org/project/cdn/releases/8.x-3.2
- https://www.drupal.org/project/cdn/releases/8.x-3.1
- …

And I _love_ that it automatically extracts the full list of contributors. It made https://www.drupal.org/project/jsonapi/releases/8.x-2.0 feel extra special, because we never realized we had so many contributors!

So: _thank you_ ❤️👏

**Comment by mglaman** [comment]
:) this is so nice I don't want to close it. But triaging the issues.

Thanks for using it!
