### ISSUE TITLE
Running drupalorg in subdirectory fails

### ISSUE THREAD

**Issue by hansfn** [mglaman/drupalorg-cli#52]
It seems `drupalorg` is meant to be run in the root of the Git repository. 

Example from `Interdiff.php`:

```
$this->repository = $client->getRepository($this->cwd);
```

Example running from `/../htdocs/git/core/modules/locale` (branch "3124942-no_translation_updat")

```
$  drupalorg -vvv issue:interdiff 3124942
Cache HIT for node:3124942
PHP Fatal error:  Uncaught Error: Call to a member function getCurrentBranch() on null in /.../vendor/mglaman/drupalorg-cli/src/Cli/Command/Issue/Interdiff.php:166
[cut]
```

Anyway, there are two "solutions" to this:

1. Add checks if $this->repository is null and abort with friendly error message.
2. Search in parent directories to find repository root. (Maybe already supported by `Gitter\Client`?)

I prefer 2 which IMHO would be a major improvement - being able to run `drupalorg` from any directory in the repository. If you don't see any problems with this, I'm willing to write a patch. (If all comands assumes that we are in the root, it will be more work - of course.)

**Comment by mglaman** [comment]
Ah, I've never used this in conjunction with working on Drupal core, which would explain why you hit this. I think we can support looking "upwards" until we hit a Git repo. I don't know if the `Gitter` client supports it, but we could add a while loop

**Comment by hansfn** [comment]
I checked - Gitter doesn't support it. But you found a proper Git command for it so, no worries.

By the way, you'll get in the same problem if you run drupalorg a subdirectory (like src or tests) for a contributed module. The problem isn't limited to core development.

**Comment by mglaman** [comment]
From #53 

> In a follow up, once #56 is merged, let's use `git rev-parse --show-toplevel` instead of `getcwd` for finding the Git repository.
> 
> I got it from https://stackoverflow.com/questions/957928/is-there-a-way-to-get-the-git-root-directory-in-one-command and works like a charm.
