### ISSUE TITLE
Coding standard - indent

### ISSUE THREAD

**Issue by hansfn** [mglaman/drupalorg-cli#60]
I have recently written some patches and noticed that in most files the indent was 2 spaces (Drupal standard), but in some files it was 4 space - random examples: src/Cli/Command/Issue/Link.php and src/Cli/Command/Command.php

I suggest providing an .editorconfig file. Maybe copy the one from Drupal core (and remove the composer block)?

**Comment by hansfn** [comment]
Thanks, that fixes it for all new commits / pull requests, but maybe we should fix all existing files too? Minor importance.

**Comment by mglaman** [comment]
I actually added phpcs and gave it a clean up prior to this

**Comment by hansfn** [comment]
OK, maybe I looked to quickly at the files. 

There are some white space issues with comments - see for example src/Cli/Command/Issue/Interdiff.php And some white-space inconsistency when defining commands. Whatever ;-)

**Comment by mglaman** [comment]
Yeah, I noticed that. phpcbf got funky 😱 adjusted them as I hit them
