### ISSUE TITLE
Undefined offset: 1 in [...]/IssueCommandBase.php on line 161

### ISSUE THREAD

**Issue by hansfn** [mglaman/drupalorg-cli#70]
... if you run an issue command on non-issue branch.

Maybe just return an empty string if no matches found in getNidFromBranch? I'll make a PR immediately.

**Comment by mglaman** [comment]
Ah, yeah. We should do `?? null` if trying pull from any preg_matches

**Comment by hansfn** [comment]
In addition we probably should print a warning if NID not found from branch name or not provided. For example `drupalorg issue:link` should not open a link if no nid present.

I have to do some house work, so any PR must wait for tomorrow. Maybe you are quicker than me.
