### ISSUE TITLE
Fallback to the `patch` command for `issue:apply`

### ISSUE THREAD

**Issue by daggerhart** [mglaman/drupalorg-cli#8]
If the working directory is not a git repo we should be able to see if the `patch` command is available and attempt to use it. Doing this will reduce the requirements on needing git installed.

Note: this will need a slightly modified command execution because if git isn't available then we cannot use a branch.

**Comment by mglaman** [comment]
Thanks for opening :) this makes the tool more useful for non-maintainers

**Comment by mglaman** [comment]
Landed!
