### ISSUE TITLE
outdated process version

### ISSUE THREAD

**Issue by Greg-Boggs** [mglaman/drupalorg-cli#95]
Since orgcli is installed globally, it conflicts with other command line tools. Is it easy to update this dependency requirement to a more recent version?
  
    - mglaman/drupalorg-cli v0.2.0 requires symfony/process ^3.0 -> found symfony/process[v3.0.0, ..., v3.4.47] but the package is fixed to v4.4.25 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

**Comment by mglaman** [comment]
Weird, it allows v4. Maybe I didn't tag a release 😬

**Comment by mglaman** [comment]
@Greg-Boggs can you try `0.3.0`?
