### ISSUE TITLE
Support Guzzle 7

### ISSUE THREAD

**Issue by dpi** [mglaman/drupalorg-cli#96]
Right now its not possible to use `drupalorg-cli` when an adjacent dependency requires Guzzle 7, such as:

 - Guzzle 7 itself
 - [php-http/guzzle7-adapter](https://github.com/php-http/guzzle7-adapter)
 - [doGit](https://github.com/dpi/dogit)

Guzzle 7 info:

 - https://github.com/guzzle/guzzle/blob/master/UPGRADING.md#60-to-70
 - https://github.com/guzzle/guzzle/blob/master/CHANGELOG.md

**Comment by dpi** [comment]
Bit of a selfish issue as to not need to resolve https://github.com/dpi/dogit/projects/1#card-65540790, but I dont think there should be a reason to require only Guzzle 6.

**Comment by hansfn** [comment]
Just a general remark: Use [cgr](https://github.com/consolidation/cgr) instead of `composer require global`. 

I don't object to supporting Guzzle 7, of course.

**Comment by dpi** [comment]
Thanks @hansfn I didnt know about cgr.

Unfortunately cgr doesnt yet work out of the box with PHP8, requiring `--ignore-platform-reqs` seems to overcome things without issue.

Once consolidation/cgr#40 is resolved I'll promote this as the way to go on dpi/dogit' README. Perhaps the same can be done for mglaman/drupalorg-cli.
